-- 50 FULLY SYNTHETIC patient records (invented names, diagnoses, dates).
INSERT INTO records (patient_name, dob, diagnosis, notes) VALUES
('Nguyễn Văn An',    '1958-03-12', 'Tăng huyết áp',              'Theo dõi huyết áp hàng tuần, dùng thuốc đều'),
('Trần Thị Bích',    '1972-07-24', 'Đái tháo đường type 2',      'HbA1c 7.2%, tái khám sau 3 tháng'),
('Lê Minh Châu',     '1985-01-05', 'Viêm họng cấp',              'Kháng sinh 5 ngày, tái khám nếu sốt'),
('Phạm Quốc Dũng',   '1964-11-30', 'Thoái hóa khớp gối',         'Vật lý trị liệu 2 buổi/tuần'),
('Hoàng Thị Én',     '1990-09-17', 'Viêm dạ dày',                'Nội soi ngày 12/08, HP âm tính'),
('Vũ Đức Phong',     '1979-05-02', 'Rối loạn lipid máu',         'Ăn kiêng, statin liều thấp'),
('Đặng Thu Giang',   '1995-12-08', 'Viêm xoang mạn',             'Rửa mũi hàng ngày, xịt corticoid'),
('Bùi Văn Hải',      '1955-02-19', 'Bệnh phổi tắc nghẽn mạn',    'Bỏ thuốc lá, thở oxy khi ngủ'),
('Đỗ Thị Hồng',      '1988-06-27', 'Thiếu máu thiếu sắt',        'Bổ sung sắt 3 tháng, kiểm tra lại CTM'),
('Ngô Gia Khánh',    '2001-04-14', 'Viêm da cơ địa',             'Dưỡng ẩm, tránh xà phòng mạnh'),
('Dương Thị Lan',    '1969-08-03', 'Sỏi thận phải 6mm',          'Uống nhiều nước, tái khám siêu âm 1 tháng'),
('Lý Văn Minh',      '1982-10-21', 'Trào ngược dạ dày thực quản','PPI 8 tuần, kê cao đầu giường'),
('Trịnh Thu Nga',    '1993-03-09', 'Viêm phế quản cấp',          'Nghỉ ngơi, thuốc ho, không kháng sinh'),
('Phan Đình Oai',    '1948-07-16', 'Suy tim độ II',              'Hạn chế muối, cân hàng ngày'),
('Võ Thị Phương',    '1977-01-28', 'Cường giáp',                 'Methimazole, kiểm tra TSH sau 6 tuần'),
('Tạ Quang Quý',     '1960-05-11', 'Gout mạn',                   'Kiêng bia rượu, allopurinol'),
('Hồ Thị Riêng',     '1999-11-04', 'Viêm kết mạc dị ứng',        'Nhỏ mắt kháng histamin'),
('Mai Văn Sơn',      '1971-09-23', 'Thoát vị đĩa đệm L4-L5',     'Hạn chế mang vác, tập McKenzie'),
('Chu Thị Tâm',      '1986-02-15', 'Đau nửa đầu Migraine',       'Ghi nhật ký cơn đau, tránh caffeine'),
('Hà Đức Uy',        '1992-08-30', 'Viêm amidan mạn',            'Cân nhắc cắt amidan nếu tái phát >4 lần/năm'),
('Lưu Thị Vân',      '1965-12-19', 'Loãng xương',                'Bổ sung canxi + vitamin D, đo DEXA hàng năm'),
('Đinh Công Vinh',   '1980-04-07', 'Viêm gan B mạn',             'Theo dõi men gan và HBV-DNA mỗi 6 tháng'),
('Trương Thị Xuân',  '1954-06-25', 'Đục thủy tinh thể',          'Hẹn mổ Phaco mắt phải'),
('Quách Văn Yên',    '1975-10-13', 'Hen phế quản',               'Xịt dự phòng hàng ngày, tránh khói bụi'),
('Kiều Thị Ánh',     '1997-05-20', 'Thiếu vitamin D',            'Bổ sung 2000 IU/ngày, phơi nắng sáng'),
('La Văn Bảo',       '1962-01-31', 'Phì đại tiền liệt tuyến',    'Tamsulosin, theo dõi PSA'),
('Ông Thị Cúc',      '1989-07-08', 'Hội chứng ruột kích thích',  'Ăn FODMAP thấp, giảm stress'),
('Ninh Đức Đạt',     '2003-09-26', 'Cận thị tiến triển',         'Kính mới -4.5D, tái khám 6 tháng'),
('Ứng Thị Em',       '1970-03-17', 'Viêm khớp dạng thấp',        'Methotrexate hàng tuần, acid folic'),
('Cao Văn Phúc',     '1984-11-09', 'Gan nhiễm mỡ độ 2',          'Giảm cân 5%, tập thể dục 150 phút/tuần'),
('Thái Thị Quyên',   '1996-06-02', 'Rối loạn lo âu',             'Tư vấn tâm lý, tái khám 2 tuần'),
('Tô Minh Rạng',     '1957-08-14', 'Nhồi máu cơ tim cũ',         'Aspirin + statin, tái khám tim mạch 3 tháng'),
('Vương Thị Sen',    '1991-02-22', 'Viêm bàng quang cấp',        'Kháng sinh 3 ngày, uống nhiều nước'),
('Ma Văn Tài',       '1978-12-05', 'Zona thần kinh',             'Kháng virus trong 72h, giảm đau'),
('Giang Thị Út',     '1966-04-18', 'Suy giáp',                   'Levothyroxine buổi sáng đói'),
('Nghiêm Đức Vượng', '1987-10-27', 'Viêm tai giữa',              'Kháng sinh 7 ngày, tái khám nội soi tai'),
('Ấu Thị Xinh',      '2000-01-15', 'Mụn trứng cá nặng',          'Isotretinoin, tránh thai bắt buộc'),
('Lạc Văn Ý',        '1953-05-29', 'Parkinson giai đoạn sớm',    'Levodopa liều thấp, tập dáng đi'),
('Sầm Thị An',       '1983-09-11', 'Sốt xuất huyết ngày 3',      'Theo dõi tiểu cầu hàng ngày, uống oresol'),
('Đàm Văn Bình',     '1994-07-04', 'Gãy xương đòn trái',         'Đeo đai số 8 trong 4 tuần'),
('Khúc Thị Chi',     '1961-11-23', 'Viêm túi mật mạn',           'Hẹn mổ nội soi cắt túi mật'),
('Ưng Đức Duy',      '1976-02-09', 'Viêm gan C mạn',             'Phác đồ DAA 12 tuần'),
('Tăng Thị Hà',      '1998-08-19', 'Thiếu máu não thoáng qua',   'Chụp MRI, aspirin dự phòng'),
('Lều Văn Kiên',     '1959-06-07', 'Ung thư đại tràng đã mổ',    'Hóa trị bổ trợ chu kỳ 4/8'),
('Ngạc Thị Loan',    '1981-03-26', 'Lupus ban đỏ hệ thống',      'Hydroxychloroquine, tránh nắng'),
('Doãn Minh Nhật',   '2002-10-31', 'Chấn thương dây chằng gối',  'MRI xác nhận đứt ACL, hẹn mổ tái tạo'),
('Bạch Thị Oanh',    '1968-12-13', 'Đau thần kinh tọa',          'Giảm đau, tập giãn cơ hình lê'),
('Ván Văn Phú',      '1973-04-01', 'Xơ gan còn bù',              'Nội soi tầm soát giãn tĩnh mạch thực quản'),
('Hùng Thị Quế',     '1990-05-16', 'Viêm lợi mạn',               'Lấy cao răng định kỳ 6 tháng'),
('Ái Văn Sáng',      '1985-08-08', 'Rối loạn tiền đình',         'Tập phục hồi chức năng tiền đình');
